# Generated by Django 5.0.6 on 2024-05-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfile',
            name='id',
        ),
        migrations.AddField(
            model_name='textfile',
            name='file_id',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
