# Generated by Django 5.0.6 on 2024-05-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textfiles', '0002_remove_textfile_id_textfile_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='section',
        ),
        migrations.AddField(
            model_name='textfile',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfile',
            name='image',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textfile',
            name='file_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
