# Generated by Django 5.0.6 on 2024-05-25 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textfiles', '0003_fileimage_remove_textfile_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='FileImage',
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textfiles.textfile'),
        ),
    ]
