# Generated by Django 5.0.6 on 2024-05-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textfiles', '0004_image_delete_fileimage_remove_textfile_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='FileImage',
        ),
    ]
