# Generated by Django 5.0.6 on 2024-05-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textfiles', '0005_rename_image_fileimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileImage',
            new_name='Image',
        ),
    ]
