# Generated by Django 5.0.6 on 2024-05-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textfiles', '0007_group_textfile_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='group',
            new_name='group_id',
        ),
    ]
