# Generated by Django 5.0.6 on 2024-05-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textfiles', '0008_rename_group_textfile_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
