# Generated by Django 5.0.6 on 2024-05-26 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textfiles', '0009_rename_group_id_textfile_group_remove_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='textfiles.group'),
        ),
    ]
