# Generated by Django 5.0.6 on 2024-05-26 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textfiles', '0010_alter_textfile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='textfiles.group'),
        ),
    ]
