# Generated by Django 5.0.6 on 2024-05-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textfiles', '0013_remove_group_id_group_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='group_id',
            new_name='group',
        ),
    ]
