# Generated by Django 5.0.6 on 2024-05-26 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textfiles', '0017_remove_group_group_id_remove_textfile_file_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='FileGroup',
        ),
    ]
