# Generated by Django 5.0.6 on 2024-05-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textfiles', '0020_remove_group_id_remove_textfile_id_group_group_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='group',
            new_name='group_id',
        ),
    ]
